'''
I gave a collection of recent news articles. Generate 10 LLM prompts for summarizing the news articles in an engaging, easy-to-digest 10-bullet format. They should focus on all the news, not on particular genres.
'''

SYSTEM_CMD_LIST = [
    '"Highlight Reel: Unraveling the Top 5 Breakthroughs of the Month": Summarize the top five most impactful breakthroughs or developments from the news articles collection, and present them as bullets, in an engaging, easy-to-digest format, complete with key takeaways.',  # noqa
    '"Innovation Spotlight: Disruptors Shaping the Future": Identify and showcase individuals, companies, or organizations from the news articles that are driving innovation and change, and provide a brief overview of their contributions and impact.',  # noqa
    '"The Intersection of Science, Technology, and Art: A Monthly Roundup": Request the LLM to curate and present a selection of news stories that highlight the fascinating ways in which science, technology, and art intersect and influence one another.',  # noqa
    '"Global Trends and Patterns: A Bird\'s - Eye View": Ask the LLM to analyze the news articles for emerging trends, patterns, or issues on a global scale, and present its findings in a cohesive and thought - provoking digest that encourages further discussion and exploration.',  # noqa
    '"The Road Ahead: Future-Focused Insights and Predictions": Have the LLM draw upon the information in the news articles to offer insightful predictions, possibilities, or scenarios for the near and distant future, and invite readers to engage in a forward-thinking conversation.',  # noqa
    '"Inspiring Solutions: Tackling Global Challenges": Request the LLM to compile and present a series of inspiring stories or case studies from the news articles that highlight innovative solutions, approaches, or initiatives being implemented to address major global challenges.',  # noqa
    '"The Ethics of Innovation: Balancing Progress and Responsibility": Have the LLM delve into the ethical considerations, dilemmas, or debates surrounding particular innovations, technologies, or breakthroughs mentioned in the news articles, and provide a balanced, thought-provoking overview of the issues at hand.',  # noqa
    '"The Power of Collaboration: Cross-Industry Partnerships and Initiatives": Ask the LLM to identify and showcase examples of successful cross-industry, interdisciplinary, or unexpected collaborations from the news articles, and explore the factors that contributed to their success and impact.',  # noqa
    '"From Lab to Market: The Commercialization of Innovative Technologies": Request the LLM to examine the process of commercializing new technologies or innovations mentioned in the news articles, including the challenges, opportunities, and potential implications for both the market and the wider world.',  # noqa
    '"The Ripple Effect: Exploring the Unintended Consequences of Innovation": Have the LLM delve into the unintended or unforeseen consequences, side-effects, or byproducts of particular innovations, technologies, or breakthroughs mentioned in the news articles, and present its findings in a digest that encourages readers to think critically and holistically about the role of innovation in society.',  # noqa
]
